### ISSUE TITLE
Add compatibility with Cura 5.7.0

### ISSUE THREAD

**Issue by eccodolf** [fieldOfView/Cura-TabbedSettingsPlugin#12] opened 2024-04-06 21:31 UTC
Due to new release of Cura 5.7.0 new release of plugin is neened. 

![image](https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/assets/37067660/93f73bc5-8a0d-47bc-b099-4f060570d4e2)

**Comment by fieldOfView** [comment] 2024-04-07 06:44
Closing as a duplicate of #10. 

See https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/releases

**Closed as completed by fieldOfView** 2024-04-07 06:44 UTC
